//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayUp.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardBlacklist
    {
        public int CardBlacklistID { get; set; }
        public string MerchantID { get; set; }
        public string CardIssuerer { get; set; }
        public string FirstSixDigits { get; set; }
        public string LastFourDigits { get; set; }
        public string CardType { get; set; }
        public string IssuingCountry { get; set; }
        public string Date { get; set; }
    }
}
