//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayUp.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public int PlanID { get; set; }
        public string MerchantID { get; set; }
        public string PlanCode { get; set; }
        public string PlanName { get; set; }
        public string PlanDescription { get; set; }
        public string PlanAmount { get; set; }
        public string Interval { get; set; }
        public string InvioiceLimit { get; set; }
        public string Date { get; set; }
    }
}
