//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayUp.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int TokenID { get; set; }
        public string MerchantID { get; set; }
        public string TokenNo { get; set; }
        public string CardType { get; set; }
        public string MaskedCardNo { get; set; }
        public string ExpiryDate { get; set; }
    }
}
