//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayUp.Core.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class URL
    {
        public int UriID { get; set; }
        public string MerchantID { get; set; }
        public string WebhookURL { get; set; }
        public string CallBackURL { get; set; }
    }
}
