//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayUp.Core.DB.STAGING
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessProfile
    {
        public int BusinessProfileID { get; set; }
        public string MerchantID { get; set; }
        public string BusinessName { get; set; }
        public string PhysicalAddress { get; set; }
        public string WebsiteLink { get; set; }
        public string FacebookLink { get; set; }
        public string TwitterLink { get; set; }
        public string InstagramLink { get; set; }
        public string YoutubeLink { get; set; }
    }
}
