//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayUp.Core.DB.STAGING
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantStatu
    {
        public int MerchantStatusID { get; set; }
        public string MerchantID { get; set; }
        public Nullable<bool> isLiveMode { get; set; }
    }
}
