//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayUp.Core.DB.STAGING
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPage
    {
        public int ProductPageID { get; set; }
        public string MerchantID { get; set; }
        public string ProductDescription { get; set; }
        public string RedirectLink { get; set; }
        public string CustomLink { get; set; }
        public string Type { get; set; }
        public string Link { get; set; }
        public string PageName { get; set; }
        public string SuccessMessage { get; set; }
        public string Date { get; set; }
    }
}
