//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayUp.Core.DB.STAGING
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int SubscriptionID { get; set; }
        public string MerchantID { get; set; }
        public string PlanID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string Amount { get; set; }
        public string Status { get; set; }
    }
}
